# Generated by Django 5.2.3 on 2025-06-13 07:05

import django.db.models.deletion
import football.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('viewers_capacity', models.IntegerField(default=0, max_length=9, validators=[football.models.positive_number_of_viewers_capacity])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Football_fields', to='accounts.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Football_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
