# Generated by Django 5.2.3 on 2025-06-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footballfield',
            options={'verbose_name': 'Football Field', 'verbose_name_plural': 'Football Fields'},
        ),
        migrations.AlterModelTable(
            name='footballfield',
            table='Football Fields',
        ),
    ]
