# Generated by Django 5.2.3 on 2025-06-13 09:38

import django.core.validators
import football.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=football.models.unique_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), football.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='viewers_capacity',
            field=models.IntegerField(default=0, validators=[football.models.positive_number_of_viewers_capacity]),
        ),
    ]
