# Generated by Django 5.2.3 on 2025-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
