# Generated by Django 5.2.3 on 2025-06-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_appointment_total_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
